version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/lilylilylily123/login-system"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"